# -*- coding: utf-8 -*-


# -*- coding: utf-8 -*-
# request id
import data_collect.sign.config as config

REQUEST_ID_HEADERS_KEY = "x-request-id"
RESPONSE_TYPE_JSON_HEADERS_KEY = "x-response-type"
RESPONSE_TYPE_JSON_HEADERS_VALUE = "json"

JAVASCRIPT_SIGN_SERVER = "javascript"
PLAYWRIGHT_SIGN_SERVER = "playwright"
PYTHON_SIGN_SERVER = "python"

XHS_PLATFORM_NAME = "xiaohongshu"
XHS_INDEX_URL = "https://www.xiaohongshu.com/"
XHS_PLAYWRIGHT_SIGN = PLAYWRIGHT_SIGN_SERVER
XHS_JAVASCRIPT_SIGN = JAVASCRIPT_SIGN_SERVER
XHS_DEFAULT_SIGN_SERVER = PLAYWRIGHT_SIGN_SERVER if config.sign_type == PLAYWRIGHT_SIGN_SERVER else XHS_JAVASCRIPT_SIGN

DOUYIN_PLATFORM_NAME = "douyin"
DOUYIN_INDEX_URL = "https://www.douyin.com/"
DOUYIN_PLAYWRIGHT_SIGN = PLAYWRIGHT_SIGN_SERVER
DOUYIN_JAVASCRIPT_SIGN = JAVASCRIPT_SIGN_SERVER
DOUYIN_DEFAULT_SIGN_SERVER = PLAYWRIGHT_SIGN_SERVER if config.sign_type == PLAYWRIGHT_SIGN_SERVER else DOUYIN_JAVASCRIPT_SIGN


BILIBILI_PLATFORM_NAME = "bilibili"
BILIBILI_INDEX_URL = "https://www.bilibili.com/"
BILIBILI_API_URL = "https://api.bilibili.com"
BILIBILI_PLAYWRIGHT_SIGN = PLAYWRIGHT_SIGN_SERVER
BILIBILI_PYTHON_SIGN = PYTHON_SIGN_SERVER
BILIBILI_DEFAULT_SIGN_SERVER = PLAYWRIGHT_SIGN_SERVER if config.sign_type == PLAYWRIGHT_SIGN_SERVER else BILIBILI_PYTHON_SIGN


ZHIHU_PLATFORM_NAME = "zhihu"
ZHIHU_JAVASCRIPT_SIGN = JAVASCRIPT_SIGN_SERVER
ZHIHU_DEFAULT_SIGN_SERVER = ZHIHU_JAVASCRIPT_SIGN

ONE_SECOND = 1
ONE_MINUTE = 60 * ONE_SECOND
ONE_HOUR = 60 * ONE_MINUTE
PLAYWRIGHT_INDEX_LOAD_TIME = 2 * ONE_SECOND
